### ISSUE TITLE
问下，怎么获取所有分类？

### ISSUE THREAD

**Issue by sidwubf** [luo1994/js-app-#23]
"categoryId":36,
"level1CategoryId":29,
"level2CategoryId":35,

这些分类id怎么获取信息？

**Comment by sidwubf** [comment]
我看代码里面只有category = {"code":200,"msg":"success","data":{"list":[{"catId":0,"catName":"品牌"},{"catId":1,"catName":"系列"},{"catId":3,"catName":"球鞋"},{"catId":6,"catName":"潮搭"},{"catId":8,"catName":"手表"},{"catId":1000119,"catName":"配件"},{"catId":7,"catName":"潮玩"},{"catId":9,"catName":"数码"},{"catId":1000008,"catName":"家电"},{"catId":726,"catName":"箱包"},{"catId":587,"catName":"美妆"},{"catId":945,"catName":"家居"}]},"status":200}这些

**Comment by luo1994** [comment]
你这个抓包看看

**Comment by sidwubf** [comment]
> 你这个抓包看看

嗯，我抓了看到了，谢谢
